### PR TITLE
Fix OSX build - dylib instead of framework

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

While the previous PR (#20) allowed building on OSX, one could not actually link to OGRE. This PR fixes this by building dylib's instead of frameworks. There is still some bug that the lib is called `Codec_FreeImage.dylib` while it should be `libCodec_FreeImage.dylib` to be correctly found late on. Not sure how to fix that.

I also removed the hack to disable precompiled headers and instead use the proper build flag (`DOGRE_ENABLE_PRECOMPILED_HEADERS=0`)

### CODE REVIEW

**Comment by wolfv** [comment]
hey @Tobias-Fischer should we wait to figure out what the naming issue of the codec_freeimage issue is or should we already merge? does it really not work? I guess this would be a bug in the upstream CMake if true?


Thanks a lot btw for this work! Super-appreciated :)

**Comment by wolfv** [comment]
btw not sure if this is useful but there are three ogre "bottles" for homebrew in this repository: https://github.com/osrf/homebrew-simulation/blob/master/Formula/ogre1.9.rb

they also seem to contain a bunch of patches

**Comment by Tobias-Fischer** [comment]
Hiya, I investigated this further and it's actually a bug (or at least incompatibility with this build) in rviz - see https://github.com/ros-visualization/rviz/blob/melodic-devel/src/rviz/ogre_helpers/render_system.cpp#L181-L183 which prepends "lib" which is not the case with this ogre build.

So I think this PR is ready to merge, just something to keep in mind for later when creating a feedstock for rviz.

**Comment by wolfv** [comment]
sounds good! 
We can remove that easily from RViz once we're there :)

**Pull request merged**
