### PR TITLE
Test rebuild of 1.10 branch

### PR DESCRIPTION
**Pull request by traversaro**
Do not merge, just a way to test problems that occured in https://github.com/conda-forge/ogre-feedstock/pull/63 .

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
My best bet is that osx fails because of the change from `sdl2:           2.0.12-he49afe7_1` to `sdl2:           2.0.18-he49afe7_0`.

**Comment by traversaro** [comment]
> My best bet is that osx fails because of the change from `sdl2: 2.0.12-he49afe7_1` to `sdl2: 2.0.18-he49afe7_0`.

I fixed the update to sdl2 2.0.20 (https://github.com/conda-forge/sdl2-feedstock/pull/25) to check if using 2.0.20 is working fine. However in the meantime we can try to pin sdl2 to 2.0.12, as the error only occurs during SWIG generation it is not a problem if then at runtime a newever sdl2 is used.

**Comment by Tobias-Fischer** [comment]
Can we close here @traversaro?

**Comment by traversaro** [comment]
Sure!

**Pull request closed without merging**
