### PR TITLE
Bump build number to 11 for 1.10

### PR DESCRIPTION
**Pull request by johnwason**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
For reasoning, see https://github.com/conda-forge/gazebo-feedstock/issues/183#issuecomment-1695015992 - we basically want to pull in a new version of pugixml

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by johnwason** [comment]
I didn't rerender because I noticed that the pinning just changed today. I don't want to cause even more version mismatching...

**Comment by Tobias-Fischer** [comment]
It seems like it's just sdl2 that is being pinned.

**Pull request merged**
