### PR TITLE
1.10arm migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Seems like this needs patching https://github.com/OGRECave/ogre/blob/v1.10.12/OgreMain/src/OgrePlatformInformation.cpp

**Comment by Tobias-Fischer** [comment]
Here's the relevant fix: https://github.com/OGRECave/ogre/commit/0873244cc06b613ca2afbcb5522fe9ef89f111c5

**Comment by wolfv** [comment]
we could also go for Ogre 1.12 only for M1?

And only allow ignition gazebo? I think Traditional Gazebo was holding us back in general, right? (cc @traversaro)

**Comment by wolfv** [comment]
The screenshot I posted of RViz running on M1 was using 1.12 I think.

**Comment by traversaro** [comment]
> And only allow ignition gazebo? I think Traditional Gazebo was holding us back in general, right? (cc @traversaro)

Actually also Classic Gazebo should work finish with Ogre 1.12, just a few rendering features are disabled (https://github.com/osrf/gazebo/issues/2686). There were some issues in the past (see https://github.com/osrf/gazebo/issues/2700), but hopefully they are not relevant anymore.

**Comment by Tobias-Fischer** [comment]
Hmmm, I think in this case we should try and get Gazebo11 working with Ogre 1.12 on the remaining platforms as well? In my opinion, we should avoid making exceptions as much as possible to avoid issues down the line.

**Comment by Tobias-Fischer** [comment]
I patched ogre 1.10 anyhow as it was easy enough, and if we want to, we can merge. I guess it doesn't hurt merging, even if we don't end up using it.

**Pull request merged**
